//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RekrutTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <remark>
    /// Database context class.
    /// </remark>
    /// <seealso cref="System.Data.Entity.DbContext" />
    public partial class RekrutDBEntities : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RekrutDBEntities"/> class.
        /// </summary>
        public RekrutDBEntities()
            : base("name=RekrutDBEntities")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Gets or writes to database Address table.
        /// </summary>
        /// <value>Addresses.</value>
        /// <permission cref="System.Security.PermissionSet"> Accessible from the outside.</permission>
        public virtual DbSet<Address> Addresses { get; set; }
        /// <summary>
        /// Gets or writes to database Agreement table.
        /// </summary>
        /// <value>Agreements.</value>
        /// <permission cref="System.Security.PermissionSet"> Accessible from the outside.</permission>
        public virtual DbSet<Agreement> Agreements { get; set; }
        /// <summary>
        /// Gets or writes to database FinancialStates table.
        /// </summary>
        /// <value>Agreements.</value>
        /// <permission cref="System.Security.PermissionSet"> Accessible from the outside.</permission>
        public virtual DbSet<FinancialState> FinancialStates { get; set; }
        /// <summary>
        /// Gets or writes to database Person table.
        /// </summary>
        /// <value>People.</value>
        /// <permission cref="System.Security.PermissionSet"> Accessible from the outside.</permission>
        public virtual DbSet<Person> People { get; set; }
    }
}
